P=read.table("D:\\Niranjan Dey\\Poliocases.csv",header=T,sep=",")
View(T)
T <- ts(P$cases , start = c(1960,2) , end = c(1975,1) , frequency = 12)
class(T)
plot(stl(T))
plot(T)
boxplot(T.mul$seasonal)
plot(aggregate(T))
boxplot(T ~ cycle(T))
plot(stl())
T.mul=decompose(T,type="mult")
T.addi=decompose(T)
time(T)
T.addi$trend # 12 pt moving avg
T.addi$figure # seasonal index
T.mul$seasonal
Tsad=(T/T.mul$seasonal)
plot(Tsad)
m1 <- lm(T~time(T))
acf(resid(m1),lag.max=30)
lm(T ~ poly(time(T), 3, raw=TRUE))
abline(lm(T ~ poly(time(T), 3)))
abline(model1)
sd(T.mul$trend[7:174]*T.mul$random[7:174]*T.mul$seasonal[7:174])
plot(ts(T.mul$random[7:174]))
acf(T.mul$random[7:174],main=random in multiplicative model)
sd(T.addi$trend[7:174]+T.addi$random[7:174]+T.addi$seasonal[7:174])
lm(T ~ poly(time(T),4,raw=TRUE))
boxplot(T~cycle(T))
gls(T~time(T))

trModel <- lm(T ~ c(1:length(T)))
plot(resid(trModel), type="l")

library(tseries)
adf.test(T)

library(forecast)
H=HoltWinters(log(T))
plot(H)
H$SSE
sqrt(H$SSE/length(T))
K=forecast(H, h=10)
plot(K)
resids=na.omit(K$residuals)
acf(resids, lag.max=40)
Box.test(resids, lag=20, type="Ljung-Box")
H=HoltWinters(T,seasonal = "mult")
acf(T.addi$random[7:174])
na.omit(T.mul$random)